EstoqueTIRDEB/Models/Itens.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EstoqueTIRDEB.Models
{
    public class Itens
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "O campo Modelo é obrigatório.")]
        public string Modelo { get; set; }

        [Display(Name = "Fabricante")]
        public string Fabricante { get; set; }

        [Display(Name = "CD")]
        public string CD { get; set; }

        [Display(Name = "Nota Fiscal")]
        public string NotaFiscal { get; set; }

        [Display(Name = "Equipamento")]
        public string Equipamento { get; set; }

        [Display(Name = "Número de Série")]
        public string NumeroSerie { get; set; }

        [Display(Name = "Patrimônio")]
        public string Patrimonio { get; set; }

        [Display(Name = "Sistema Operacional")]
        public string SistemaOperacional { get; set; }

        [Display(Name = "Departamento/Setor")]
        public string DepartamentoSetor { get; set; }

        [Display(Name = "Hostname")]
        public string Hostname { get; set; }

        [Required(ErrorMessage = "O campo Data de Aquisição é obrigatório.")]
        [DataType(DataType.Date)]
        public DateTime DataAquisicao { get; set; }

        // Propriedade calculada para tempo aproximado de uso em dias
        public int TempoAproximadoDeUso
        {
            get
            {
                TimeSpan tempoDeUso = DateTime.Today - DataAquisicao.Date;
                return tempoDeUso.Days;
            }
        }

        [Range(0, int.MaxValue, ErrorMessage = "A quantidade deve ser um valor positivo.")]
        public int Quantidade { get; set; }

        [Display(Name = "Categoria")]
        public int CategoriaId { get; set; }

        public Categoria Categoria { get; set; }

        public Itens()
        {
        }

        public Itens(int id, string nome, string modelo, string fabricante, string equipamento, string numeroSerie, string especificações, string patrimonio, string sistemaOperacional, string departamentoSetor, string hostname, DateTime dataAquisicao, int quantidade, int categoriaId, Categoria categoria) : this(id, modelo)
        {
            Equipamento = equipamento;
            NumeroSerie = numeroSerie;
            Patrimonio = patrimonio;
            SistemaOperacional = sistemaOperacional;
            DepartamentoSetor = departamentoSetor;
            Hostname = hostname;
            DataAquisicao = dataAquisicao;
            Quantidade = quantidade;
            CategoriaId = categoriaId;
            Categoria = categoria;
        }

        public Itens(int id, string modelo)
        {
            Id = id;
            Modelo = modelo;
        }

        

    }
}

EstoqueTIRDEB/Controllers/ItensController.cs
using CsvHelper;
using CsvHelper.Configuration;
using EstoqueTIRDEB.Data;
using EstoqueTIRDEB.Models;
using EstoqueTIRDEB.Models.ViewModels;
using EstoqueTIRDEB.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace EstoqueTIRDEB.Controllers
{
    public class ItensController : Controller
    {

        private readonly ItensService _itensService;
        private readonly EstoqueService _estoqueservice;
        private readonly CategoriaService _categoriaService;
        private readonly EstoqueTIRDEBContext _context;
        private readonly RetiradaEstoqueService _retiradaEstoqueService;
        private readonly ExcelService _excelService;

        // Construtor que aceita as dependências necessárias
        public ItensController(ItensService itensService, EstoqueService estoqueService, CategoriaService categoriaService, EstoqueTIRDEBContext context, RetiradaEstoqueService retiradaEstoqueService, ExcelService excelService)
        {
            _itensService = itensService;
            _estoqueservice = estoqueService;
            _categoriaService = categoriaService;
            _context = context;
            _retiradaEstoqueService = retiradaEstoqueService;
            _excelService = excelService;
        }

        // GET: ItensController
        public ActionResult Index()
        {
            var itensComCategorias = _itensService.FindAllWithCategoria(); // Método para carregar os itens com suas categorias

            return View(itensComCategorias);
        }

        // GET: ItensController/Details/5
        public IActionResult DetalhesQuantidade(int itemId)
        {
            var viewModel = _estoqueservice.GetDetalhesQuantidadeViewModel(itemId);

            if (viewModel == null)
            {
                return RedirectToAction("Index", "Home");
            }

            return View(viewModel);
        }

        public IActionResult ListarItensPorCategoria(int categoriaId)
        {
            var itens = _itensService.ListarPorCategoria(categoriaId);
            return View(itens);
        }

        [HttpGet]
        public IActionResult AdicionarItemAoEstoque()
        {
            // Aqui você pode retornar a view de cadastro de item
            return View();
        }

        [HttpPost]
        public IActionResult AdicionarItemAoEstoque(Itens item, int categoriaId)
        {
            _estoqueservice.AdicionarItemAoEstoque(item, categoriaId);
            return RedirectToAction("Index", "Home"); // Ou outra ação desejada
        }

        [HttpPost]
        public IActionResult AdicionarRemover(int itemId)
        {
            // Lógica para adicionar e remover o item
            return RedirectToAction("ListarItensPorCategoria", new { categoriaId = itemId });
        }

        public IActionResult Create()
        {
            var categorias = _categoriaService.GetAll();
            ViewBag.Categorias = new SelectList(categorias, "Id", "Nome");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Itens itens, int quantidade)
        {
            if (ModelState.IsValid)
            {
                // Define a quantidade inicial do item
                itens.Quantidade = quantidade;

                _itensService.Insert(itens);
                return RedirectToAction(nameof(Index));
            }
            var categorias = _categoriaService.GetAll();
            ViewBag.Categorias = new SelectList(categorias, "Id", "Nome", itens.CategoriaId);
            return View(itens);
        }


        // GET: ItensController/Edit/5
        public ActionResult Edit(int id)
        {
            var item = _itensService.FindById(id);
            if (item == null)
            {
                return NotFound();
            }

            var categorias = _categoriaService.GetAll(); // Carregar todas as categorias disponíveis
            ViewBag.Categorias = new SelectList(categorias, "Id", "Nome", item.CategoriaId); // Passar as categorias para a view

            return View(item);
        }

        // POST: ItensController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Itens item, int quantidade)
        {
            if (id != item.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    // Atualiza a quantidade do item
                    item.Quantidade = quantidade;
                    _itensService.Update(item);
                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    // Se ocorrer algum erro ao atualizar, recarrega a lista de categorias e retorna a view com o item
                    var categorias = _categoriaService.GetAll();
                    ViewBag.Categorias = new SelectList(categorias, "Id", "Nome", item.CategoriaId);
                    return View(item);
                }
            }

            // Se o modelo não for válido, recarrega a lista de categorias e retorna a view com o item
            var categoriasInvalidas = _categoriaService.GetAll();
            ViewBag.Categorias = new SelectList(categoriasInvalidas, "Id", "Nome", item.CategoriaId);
            return View(item);
        }

        // GET: ItensController/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var obj = _itensService.FindById(id.Value);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        // POST: ItensController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            _itensService.Remove(id);
            return RedirectToAction(nameof(Index));
        }

        // Outros métodos do controller

        // GET: Itens/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Itens.FirstOrDefaultAsync(m => m.Id == id);
            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        // GET: Itens/RetirarQuantidade/5
        public async Task<IActionResult> RetirarQuantidade(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Itens.FirstOrDefaultAsync(m => m.Id == id);
            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        // POST: Itens/RetirarQuantidade/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RetirarQuantidade(int id, int quantidadeRetirada)
        {
            var item = await _context.Itens.FindAsync(id);
            if (item == null)
            {
                return NotFound();
            }

            if (quantidadeRetirada <= item.Quantidade)
            {
                item.Quantidade -= quantidadeRetirada;
                await _context.SaveChangesAsync();

                // Criar um registro de retirada de estoque
                var retiradaEstoque = new RetiradaEstoque
                {
                    ItemId = item.Id,
                    QuantidadeRetirada = quantidadeRetirada,
                    DataHoraRetirada = DateTime.Now
                };
                _context.RetiradaEstoque.Add(retiradaEstoque);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            else
            {
                // Retornar uma mensagem de erro informando que a quantidade a ser retirada é maior do que a quantidade disponível
                ModelState.AddModelError(string.Empty, "A quantidade a ser retirada é maior do que a quantidade disponível.");
                return View(item);
            }
        }

        [HttpGet]
        public IActionResult UploadExcel()
        {
            return View("UploadExcel");
        }

        [HttpPost]
        public async Task<IActionResult> UploadExcel(IFormFile excelFile)
        {
            if (excelFile == null || excelFile.Length == 0)
            {
                return Content("Arquivo não selecionado");
            }

            using (var reader = new StreamReader(excelFile.OpenReadStream()))
            {
                var config = new CsvConfiguration(CultureInfo.InvariantCulture)
                {
                    Delimiter = ",",
                    HasHeaderRecord = true // Se a primeira linha contém o cabeçalho
                };

                using (var csv = new CsvReader(reader, config))
                {
                    var records = csv.GetRecords<Itens>();

                    foreach (var item in records)
                    {
                        if (ModelState.IsValid)
                        {
                            _itensService.Insert(item);
                        }
                        else
                        {
                            var categorias = _categoriaService.GetAll();
                            ViewBag.Categorias = new SelectList(categorias, "Id", "Nome", item.CategoriaId);
                            return View("Create", item);
                        }
                    }
                }
            }

EstoqueTIRDEB/Views/Itens/Adicionar.cshtml
@model IEnumerable<EstoqueTIRDEB.Models.Itens>

@{
    ViewData["Title"] = "Itens por Categoria";
    Layout = "_Layout";
}

<h2>Itens por Categoria</h2>

<table class="table">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Modelo</th>
            <th>Especificações</th>
            <th>Data de Aquisição</th>
            <th>Quantidade</th>
            <th>Categoria</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Equipamento</td>
                <td>@item.Modelo</td>
                <td>@item.DataAquisicao</td>
                <td>@item.Quantidade</td>
                <td>@item.Categoria</td>
                <td>
                    <form asp-controller="Itens" asp-action="AdicionarRemover" method="post">
                        <input type="hidden" name="itemId" value="@item.Id" />
                        <button type="submit" class="btn btn-primary">Remover e Adicionar</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

EstoqueTIRDEB/Views/Itens/AdicionarQuantidade.cshtml
@model IEnumerable<EstoqueTIRDEB.Models.Itens>

@{
    ViewData["Title"] = "Itens por Categoria";
    Layout = "_Layout";
}

<h2>Itens por Categoria</h2>

<table class="table">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Modelo</th>
            <th>Especificações</th>
            <th>Data de Aquisição</th>
            <th>Quantidade</th>
            <th>Categoria</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Equipamento</td>
                <td>@item.Modelo</td>
                <td>@item.DataAquisicao</td>
                <td>@item.Quantidade</td>
                <td>@item.Categoria.Nome</td> <!-- Exibir o nome da categoria -->
                <td>
                    <form asp-controller="Itens" asp-action="AdicionarQuantidade" method="post">
                        <input type="hidden" name="id" value="@item.Id" />
                        <input type="number" name="quantidade" min="1" value="1" /> <!-- Campo para adicionar quantidade -->
                        <button type="submit" class="btn btn-primary">Adicionar Quantidade</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

EstoqueTIRDEB/Views/Itens/Create.cshtml
@model EstoqueTIRDEB.Models.Itens

@{
    ViewData["Title"] = "Adicionar Item ao Estoque";
    Layout = "_Layout";
}

<h2>Adicionar Item ao Estoque</h2>

<form asp-action="Create">
    <div class="form-group">
        <label asp-for="CD" class="control-label">CD</label>
        <input asp-for="CD" class="form-control" />
        <span asp-validation-for="CD" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Fabricante" class="control-label">Fabricante</label>
        <input asp-for="Fabricante" class="form-control" />
        <span asp-validation-for="Fabricante" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Equipamento" class="control-label">Equipamento</label>
        <input asp-for="Equipamento" class="form-control" />
        <span asp-validation-for="Equipamento" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Modelo" class="control-label">Modelo</label>
        <input asp-for="Modelo" class="form-control" />
        <span asp-validation-for="Modelo" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="NotaFiscal" class="control-label">N/S</label>
        <input asp-for="NotaFiscal" class="form-control" />
        <span asp-validation-for="NotaFiscal" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Patrimonio" class="control-label">Patrimônio</label>
        <input asp-for="Patrimonio" class="form-control" />
        <span asp-validation-for="Patrimonio" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="SistemaOperacional" class="control-label">Sistema Operacional</label>
        <input asp-for="SistemaOperacional" class="form-control" />
        <span asp-validation-for="SistemaOperacional" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="DepartamentoSetor" class="control-label">Departamento (Setor)</label>
        <input asp-for="DepartamentoSetor" class="form-control" />
        <span asp-validation-for="DepartamentoSetor" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Hostname" class="control-label">Hostname</label>
        <input asp-for="Hostname" class="form-control" />
        <span asp-validation-for="Hostname" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="DataAquisicao" class="control-label">Data de Aquisição</label>
        <input asp-for="DataAquisicao" class="form-control" />
        <span asp-validation-for="DataAquisicao" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="CategoriaId" class="control-label">Categoria</label>
        <select asp-for="CategoriaId" class="form-control" asp-items="ViewBag.Categorias"></select>
        <span asp-validation-for="CategoriaId" class="text-danger"></span>
    </div>


    <div class="form-group">
        <label asp-for="Quantidade" class="control-label">Quantidade</label>
        <input asp-for="Quantidade" class="form-control" />
        <span asp-validation-for="Quantidade" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Create</button>
</form>




@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EstoqueTIRDEB/Views/Itens/Delete.cshtml
@model EstoqueTIRDEB.Models.Itens

@{
    ViewData["Title"] = "Delete";
    Layout = "_Layout";
}

<h2>Delete</h2>

<h3>Você tem certeza que deseja deletar este item?</h3>
<div>
    <h4>Itens</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Equipamento)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Equipamento)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Modelo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DataAquisicao)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DataAquisicao)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Quantidade)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Quantidade)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Fabricante)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Fabricante)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Patrimonio)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Patrimonio)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TempoAproximadoDeUso)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TempoAproximadoDeUso)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

EstoqueTIRDEB/Views/Itens/Details.cshtml
@model EstoqueTIRDEB.Models.Itens
@{
    ViewData["Title"] = "Detalhes do Item";
    Layout = "_Layout";
}

<h2>Remover Item</h2>

<div class="card">
    <div class="card-body">
        <h4 class="card-title">Detalhes do Item</h4>
        <div class="row">
            <div class="col-md-6">
                <ul class="list-group">
                    <li class="list-group-item">Nome: @Html.DisplayFor(model => model.Nome)</li>
                    <li class="list-group-item">Modelo: @Html.DisplayFor(model => model.Modelo)</li>
                    <li class="list-group-item">Especificações: @Html.DisplayFor(model => model.Especificações)</li>
                    <li class="list-group-item">Data de Aquisição: @Html.DisplayFor(model => model.DataAquisicao)</li>
                    <li class="list-group-item">Quantidade: @Html.DisplayFor(model => model.Quantidade)</li>
                    <li class="list-group-item">Categoria: @Html.DisplayFor(model => model.Categoria)</li>
                </ul>
            </div>
        </div>
        <form asp-controller="Itens" asp-action="RemoverQuantidade" method="post">
            <input type="hidden" name="id" value="@Model.Id" />
            <div class="form-group mt-3">
                <label for="quantidade">Quantidade a Remover:</label>
                <input type="number" class="form-control" id="quantidade" name="quantidade" value="1" min="1">
            </div>
            <button type="submit" class="btn btn-danger">Remover</button>
        </form>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            // Adiciona um evento de clique ao botão de remoção
            $("#btn-remover").on("click", function () {
                // Obtém o ID do item e a quantidade a ser removida
                var itemId = "@Model.Id";
                var quantidade = $("#quantidade").val();

                // Solicita ao servidor para remover o item com a quantidade especificada
                $.ajax({
                    url: "/Itens/RemoverItem",
                    method: "POST",
                    data: { itemId: itemId, quantidade: quantidade },
                    success: function () {
                        // Redireciona para a página de detalhes do item após a remoção bem-sucedida
                        window.location.href = "/Itens/Details/" + itemId;
                    },
                    error: function (xhr, status, error) {
                        // Lida com erros de remoção, se necessário
                        console.error(xhr.responseText);
                    }
                });
            });
        });
    </script>
}

EstoqueTIRDEB/Views/Itens/Index.cshtml
@model IEnumerable<EstoqueTIRDEB.Models.Itens>
@inject EstoqueTIRDEB.Services.EstoqueService _estoqueService
@inject EstoqueTIRDEB.Services.ItensService _itensService

@{
    ViewData["Title"] = "Index";
    Layout = "_Layout";
}

<style>
    /* Estilo para o corpo da página */
    body {
        background-color: #f8f9fa; /* Cor de fundo da página */
    }

    /* Estilo para o título */
    h2 {
        color: #343a40; /* Cor do título */
    }

    /* Estilo para a tabela */
    .table {
        width: 100%; /* Definindo a largura da tabela para ocupar 100% da largura da tela */
        padding-left: 10%;
        background-color: #fff; /* Cor de fundo da tabela */
        margin-bottom: 50%; /* Margem inferior da tabela */
    }

        /* Estilo para o cabeçalho da tabela */
        .table thead th {
            background-color: #343a40; /* Cor de fundo do cabeçalho da tabela */
            color: #fff; /* Cor do texto do cabeçalho da tabela */
        }

        /* Estilo para as células da tabela */
        .table tbody td {
            color: #495057; /* Cor do texto das células da tabela */
        }

    /* Estilo para os botões de ação */
    .btn {
        margin-right: 5px; /* Margem direita dos botões */
    }

    /* Estilo para o rodapé */
    footer {
        text-align: center; /* Alinhamento do texto */
        padding: 20px 0; /* Preenchimento interno do rodapé */
        background-color: #f8f9fa; /* Cor de fundo do rodapé */
        margin-top: 20px; /* Margem superior do rodapé */
        color: #495057; /* Cor do texto do rodapé */
    }
</style>

<body>
    <h2 class="title">Itens</h2>

    <p>
        <a asp-action="Create" class="btn btn-default">Adicionar Item</a> <a asp-controller="Itens" asp-action="UploadExcel" class="btn btn-primary">Enviar arquivo Excel</a>
    </p>

    <table class="table">
        <thead>
            <tr>
                <th>CD</th>
                <th>Equipamento</th>
                <th>Modelo</th>
                <th>Quantidade</th>
                <th>Categoria</th>
                <th>Fabricante</th>
                <th>Patrimonio</th>
                <th>Tempo Aproximado</th>
                <th>Opções</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                // Calcula o tempo aproximado de uso apenas se a quantidade for maior que zero
                int tempoAproximadoDeUso = item.Quantidade > 0 ? _itensService.CalcularTempoAproximadoDeUso(item) : 0;

                <tr>
                    <td>@item.CD</td>
                    <td>@item.Equipamento</td>
                    <td>@item.Modelo</td>
                    <td>@item.Quantidade</td>
                    <td>@(item.Categoria != null ? item.Categoria.Nome : "")</td>
                    <td>@item.Fabricante</td>
                    <td>@item.Patrimonio</td>
                    <td>@tempoAproximadoDeUso Dias</td>
                    <td>
                        <div class="btn-group">
                            <a class="btn btn-primary action-btn" asp-action="RetirarQuantidade" asp-route-id="@item.Id">Remover</a>
                            <a class="btn btn-primary action-btn" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                            <a class="btn btn-danger action-btn" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>

</body>

EstoqueTIRDEB/Views/Itens/RetirarQuantidade.cshtml
@model EstoqueTIRDEB.Models.Itens
@{
    ViewData["Title"] = "Detalhes do Item";
    Layout = "_Layout";
}

<h2>Remover Item</h2>

<div class="card">
    <div class="card-body">
        <h4 class="card-title">Detalhes do Item</h4>
        <div class="row">
            <div class="col-md-6">
                <ul class="list-group">
                    <li class="list-group-item">Nome: @Html.DisplayFor(model => model.Equipamento)</li>
                    <li class="list-group-item">Modelo: @Html.DisplayFor(model => model.Modelo)</li>
                    <li class="list-group-item">Data de Aquisição: @Html.DisplayFor(model => model.DataAquisicao)</li>
                    <li class="list-group-item">Quantidade: @Html.DisplayFor(model => model.Quantidade)</li>
                    <li class="list-group-item">Categoria: @Html.DisplayFor(model => model.Categoria)</li>
                </ul>
            </div>
        </div>
        <form asp-controller="Itens" asp-action="RetirarQuantidade" method="post">
            <input type="hidden" name="id" value="@Model.Id" />
            <div class="form-group mt-3">
                <label for="quantidade">Quantidade a Remover:</label>
                <input type="number" class="form-control" id="quantidade" name="quantidadeRetirada" value="1" min="1">
            </div>
            <button type="submit" class="btn btn-danger">Remover</button>
        </form>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            // Adiciona um evento de clique ao botão de remoção
            $("#btn-remover").on("click", function () {
                // Obtém o ID do item e a quantidade a ser removida
                var itemId = "@Model.Id";
                var quantidade = $("#quantidade").val();

                // Solicita ao servidor para remover o item com a quantidade especificada
                $.ajax({
                    url: "/Itens/RemoverItem",
                    method: "POST",
                    data: { itemId: itemId, quantidade: quantidade },
                    success: function () {
                        // Redireciona para a página de detalhes do item após a remoção bem-sucedida
                        window.location.href = "/Itens/Details/" + itemId;
                    },
                    error: function (xhr, status, error) {
                        // Lida com erros de remoção, se necessário
                        console.error(xhr.responseText);
                    }
                });
            });
        });
    </script>
}

EstoqueTIRDEB/Views/Itens/UploadExcel.cshtml
@{
    ViewData["Title"] = "Upload de arquivo Excel";
    Layout = "_Layout";
}

<h2>Upload de arquivo Excel</h2>

<form asp-controller="Itens" asp-action="UploadExcel" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label for="excelFile">Selecione o arquivo Excel:</label>
        <input type="file" id="excelFile" name="excelFile" class="form-control-file">
    </div>
    <button type="submit" class="btn btn-primary">Enviar</button>
</form>